import type { WorkstationCard } from './workstation.types'

export const MOCK_WORKSTATION_CARDS: WorkstationCard[] = [
  {
    id: 'wc-001',
    title: 'Follow up with Sarah Mitchell on quote',
    description: 'Honda CR-V EX-L quote sent — needs response follow-up',
    columnId: 'today',
    linkedObjectType: 'lead',
    linkedObjectId: 'lead-001',
    priority: 'high',
    queueType: 'sales',
    dueAt: '2025-01-17T17:00:00Z',
    assigneeName: 'John Smith',
    requiresApproval: false,
    sourceEventName: 'quote_sent',
    tags: ['follow-up', 'hot-lead'],
    createdAt: '2025-01-15T12:15:00Z',
    updatedAt: '2025-01-16T08:00:00Z',
  },
  {
    id: 'wc-002',
    title: 'Complete F&I menu for Johnson deal',
    description: 'Ford F-150 XLT deal funded — F&I products need finalization',
    columnId: 'in_progress',
    linkedObjectType: 'deal',
    linkedObjectId: 'deal-001',
    priority: 'high',
    queueType: 'finance',
    dueAt: '2025-01-17T15:00:00Z',
    assigneeName: 'Lisa Chen',
    requiresApproval: false,
    sourceEventName: 'deal_funded',
    tags: ['f&i'],
    createdAt: '2025-01-14T19:00:00Z',
    updatedAt: '2025-01-16T09:30:00Z',
  },
  {
    id: 'wc-003',
    title: 'Review trade value override request',
    description: '2019 Toyota Camry — proposed $14,500 → $15,200',
    columnId: 'inbox',
    linkedObjectType: 'approval',
    linkedObjectId: 'app-001',
    priority: 'medium',
    queueType: 'management',
    assigneeName: 'Manager Review',
    requiresApproval: true,
    sourceEventName: 'approval_requested',
    tags: ['trade', 'approval'],
    createdAt: '2025-01-16T13:22:00Z',
    updatedAt: '2025-01-16T13:22:00Z',
  },
  {
    id: 'wc-004',
    title: 'Schedule recon for Tesla Model S',
    description: '78 days in stock — aging threshold exceeded',
    columnId: 'inbox',
    linkedObjectType: 'inventory_unit',
    linkedObjectId: 'inv-003',
    priority: 'medium',
    queueType: 'recon',
    assigneeName: 'Mike Torres',
    requiresApproval: false,
    sourceEventName: 'unit_hit_aging_threshold',
    tags: ['aging', 'recon'],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'wc-005',
    title: 'Contact Elena Rodriguez',
    description: 'Trade-in appraisal lead — score 78, needs qualification',
    columnId: 'today',
    linkedObjectType: 'lead',
    linkedObjectId: 'lead-003',
    priority: 'medium',
    queueType: 'bdc',
    assigneeName: 'John Smith',
    requiresApproval: false,
    sourceEventName: 'lead_created',
    tags: ['new-lead', 'trade-in'],
    createdAt: '2025-01-16T09:15:00Z',
    updatedAt: '2025-01-16T09:15:00Z',
  },
  {
    id: 'wc-006',
    title: 'Process Mitchell deal paperwork',
    description: 'Quote accepted — prepare deal structure for signing',
    columnId: 'waiting',
    linkedObjectType: 'deal',
    linkedObjectId: 'deal-002',
    priority: 'high',
    queueType: 'finance',
    assigneeName: 'Lisa Chen',
    requiresApproval: false,
    sourceEventName: 'quote_accepted',
    tags: ['deal-prep'],
    createdAt: '2025-01-15T14:00:00Z',
    updatedAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'wc-007',
    title: 'Review aging inventory report',
    description: '1 unit past 60-day threshold — wholesale decision needed',
    columnId: 'inbox',
    linkedObjectType: 'inventory_unit',
    linkedObjectId: 'inv-003',
    priority: 'low',
    queueType: 'management',
    requiresApproval: false,
    sourceEventName: 'unit_hit_aging_threshold',
    tags: ['aging', 'report'],
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'wc-008',
    title: 'Johnson deal delivery confirmation',
    description: 'F-150 XLT delivery scheduled and completed',
    columnId: 'done',
    linkedObjectType: 'deal',
    linkedObjectId: 'deal-001',
    priority: 'medium',
    queueType: 'sales',
    assigneeName: 'John Smith',
    requiresApproval: false,
    sourceEventName: 'vehicle_delivered',
    tags: ['delivery'],
    createdAt: '2025-01-14T20:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
]
