import type { ReportTemplate } from './reporting.types'

export const REPORT_TEMPLATES: ReportTemplate[] = [
  // ── Executive ──────────────────────────────────────────────────────────────
  {
    id: 'exec-daily-summary',
    name: 'Daily Executive Summary',
    description: 'High-level store metrics for today: units sold, gross, leads, and open exceptions.',
    category: 'executive',
    tags: ['daily', 'summary', 'executive'],
    icon: 'ChartBar',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'metric', label: 'Metric', format: 'text' },
      { field: 'today', label: 'Today', format: 'number' },
      { field: 'mtd', label: 'MTD', format: 'number' },
      { field: 'goal', label: 'Goal', format: 'number' },
      { field: 'variance', label: 'Variance', format: 'number' },
    ],
    defaultFilters: [{ field: 'date', operator: 'eq', value: 'today' }],
    defaultSortBy: 'metric',
  },
  {
    id: 'exec-weekly-summary',
    name: 'Weekly Executive Summary',
    description: 'Rolling 7-day performance overview across sales, inventory, and back-office.',
    category: 'executive',
    tags: ['weekly', 'summary', 'executive'],
    icon: 'CalendarBlank',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'metric', label: 'Metric', format: 'text' },
      { field: 'this_week', label: 'This Week', format: 'number' },
      { field: 'last_week', label: 'Last Week', format: 'number' },
      { field: 'change_pct', label: '% Change', format: 'number' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'week_start' }],
    defaultSortBy: 'metric',
  },
  {
    id: 'exec-mtd-summary',
    name: 'MTD Executive Summary',
    description: 'Month-to-date performance rolled up across all departments.',
    category: 'executive',
    tags: ['monthly', 'mtd', 'executive'],
    icon: 'TrendUp',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'department', label: 'Department', format: 'text' },
      { field: 'mtd_actual', label: 'MTD Actual', format: 'number' },
      { field: 'mtd_goal', label: 'MTD Goal', format: 'number' },
      { field: 'pacing', label: 'Pacing', format: 'badge' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'month_start' }],
    defaultGroupBy: 'department',
    defaultSortBy: 'department',
  },
  {
    id: 'exec-store-health',
    name: 'Store Health Snapshot',
    description: 'Quick red/yellow/green health indicators across all key operational areas.',
    category: 'executive',
    tags: ['health', 'kpi', 'executive'],
    icon: 'Heartbeat',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'area', label: 'Area', format: 'text' },
      { field: 'status', label: 'Status', format: 'badge' },
      { field: 'open_items', label: 'Open Items', format: 'number' },
      { field: 'oldest_days', label: 'Oldest (Days)', format: 'number' },
    ],
    defaultFilters: [],
    defaultSortBy: 'area',
  },
  {
    id: 'exec-performance-pulse',
    name: 'Performance Pulse Report',
    description: 'Real-time pulse across gross, volume, conversion, and customer satisfaction.',
    category: 'executive',
    tags: ['performance', 'pulse', 'executive'],
    icon: 'Lightning',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'kpi', label: 'KPI', format: 'text' },
      { field: 'current', label: 'Current', format: 'number' },
      { field: 'target', label: 'Target', format: 'number' },
      { field: 'status', label: 'Status', format: 'badge' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'month_start' }],
    defaultSortBy: 'kpi',
  },

  // ── Inventory ──────────────────────────────────────────────────────────────
  {
    id: 'inv-snapshot',
    name: 'Current Inventory Snapshot',
    description: 'Full view of all active inventory with status, days-in-stock, and pricing.',
    category: 'inventory',
    tags: ['inventory', 'snapshot', 'active'],
    icon: 'Car',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text', width: 100 },
      { field: 'year_make_model', label: 'Vehicle', format: 'text', width: 200 },
      { field: 'status', label: 'Status', format: 'badge', width: 120 },
      { field: 'days_in_stock', label: 'Days In Stock', format: 'number', width: 120 },
      { field: 'list_price', label: 'List Price', format: 'currency', width: 120 },
      { field: 'cost', label: 'Cost', format: 'currency', width: 120 },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Sold' }],
    defaultSortBy: 'days_in_stock',
  },
  {
    id: 'inv-aging',
    name: 'Aging Inventory Report',
    description: 'Units aged 30, 60, and 90+ days with recon status and floor plan exposure.',
    category: 'inventory',
    tags: ['aging', 'inventory', 'floor-plan'],
    icon: 'Timer',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'days_in_stock', label: 'Days In Stock', format: 'number' },
      { field: 'age_bucket', label: 'Age Bucket', format: 'badge' },
      { field: 'total_invested', label: 'Total Invested', format: 'currency' },
      { field: 'recon_status', label: 'Recon Status', format: 'badge' },
    ],
    defaultFilters: [{ field: 'days_in_stock', operator: 'gte', value: 30 }],
    defaultSortBy: 'days_in_stock',
  },
  {
    id: 'inv-by-status',
    name: 'Inventory by Status',
    description: 'Count and value breakdown of inventory grouped by status.',
    category: 'inventory',
    tags: ['inventory', 'status', 'grouped'],
    icon: 'ListBullets',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'status', label: 'Status', format: 'badge' },
      { field: 'unit_count', label: 'Units', format: 'number' },
      { field: 'total_list', label: 'Total List', format: 'currency' },
      { field: 'avg_days', label: 'Avg Days', format: 'number' },
    ],
    defaultFilters: [],
    defaultGroupBy: 'status',
    defaultSortBy: 'unit_count',
  },
  {
    id: 'inv-by-make-model',
    name: 'Inventory by Make/Model',
    description: 'Units grouped by make and model with average cost, price, and age.',
    category: 'inventory',
    tags: ['inventory', 'make', 'model'],
    icon: 'Tag',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'make', label: 'Make', format: 'text' },
      { field: 'model', label: 'Model', format: 'text' },
      { field: 'unit_count', label: 'Units', format: 'number' },
      { field: 'avg_list_price', label: 'Avg List', format: 'currency' },
      { field: 'avg_days_in_stock', label: 'Avg Days', format: 'number' },
    ],
    defaultFilters: [],
    defaultGroupBy: 'make',
    defaultSortBy: 'unit_count',
  },
  {
    id: 'inv-featured',
    name: 'Featured vs Non-Featured',
    description: 'Comparison of featured vs non-featured listings with visibility scores.',
    category: 'inventory',
    tags: ['inventory', 'featured', 'marketing'],
    icon: 'Star',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'is_featured', label: 'Featured', format: 'badge' },
      { field: 'photo_count', label: 'Photos', format: 'number' },
      { field: 'days_in_stock', label: 'Days', format: 'number' },
    ],
    defaultFilters: [],
    defaultGroupBy: 'is_featured',
    defaultSortBy: 'days_in_stock',
  },
  {
    id: 'inv-retail-vs-wholesale',
    name: 'Retail vs Wholesale Visibility',
    description: 'Units separated by retail and wholesale channels with channel-specific metrics.',
    category: 'inventory',
    tags: ['inventory', 'retail', 'wholesale'],
    icon: 'Storefront',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'channel', label: 'Channel', format: 'badge' },
      { field: 'unit_count', label: 'Units', format: 'number' },
      { field: 'avg_list_price', label: 'Avg List', format: 'currency' },
      { field: 'listed_online', label: 'Listed Online', format: 'number' },
    ],
    defaultFilters: [],
    defaultGroupBy: 'channel',
    defaultSortBy: 'channel',
  },
  {
    id: 'inv-missing-photos',
    name: 'Inventory Missing Photos',
    description: 'All active units with fewer than the minimum required photo count.',
    category: 'inventory',
    tags: ['inventory', 'photos', 'marketing', 'quality'],
    icon: 'ImageBroken',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'photo_count', label: 'Photos', format: 'number' },
      { field: 'days_in_stock', label: 'Days In Stock', format: 'number' },
      { field: 'list_price', label: 'List Price', format: 'currency' },
    ],
    defaultFilters: [{ field: 'photo_count', operator: 'lt', value: 10 }],
    defaultSortBy: 'photo_count',
  },
  {
    id: 'inv-cost-recon',
    name: 'Inventory Cost/Recon Summary',
    description: 'Cost breakdown including purchase price, recon spend, and total investment per unit.',
    category: 'inventory',
    tags: ['inventory', 'cost', 'recon'],
    icon: 'Coins',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'purchase_price', label: 'Purchase', format: 'currency' },
      { field: 'recon_cost', label: 'Recon', format: 'currency' },
      { field: 'other_costs', label: 'Other', format: 'currency' },
      { field: 'total_invested', label: 'Total Invested', format: 'currency' },
    ],
    defaultFilters: [],
    defaultSortBy: 'total_invested',
  },
  {
    id: 'inv-stuck-recon',
    name: 'Units Stuck in Recon',
    description: 'Vehicles that have been in recon for longer than the expected lead time.',
    category: 'inventory',
    tags: ['inventory', 'recon', 'stuck', 'fixed-ops'],
    icon: 'Wrench',
    dataSource: 'fixed_ops',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'recon_start_date', label: 'Recon Start', format: 'date' },
      { field: 'days_in_recon', label: 'Days In Recon', format: 'number' },
      { field: 'recon_status', label: 'Status', format: 'badge' },
      { field: 'recon_cost', label: 'Recon Spend', format: 'currency' },
    ],
    defaultFilters: [{ field: 'days_in_recon', operator: 'gt', value: 7 }],
    defaultSortBy: 'days_in_recon',
  },
  {
    id: 'inv-pricing-exceptions',
    name: 'Inventory Pricing Exceptions',
    description: 'Units priced outside acceptable margin thresholds or missing list prices.',
    category: 'inventory',
    tags: ['inventory', 'pricing', 'exceptions'],
    icon: 'WarningCircle',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'list_price', label: 'List Price', format: 'currency' },
      { field: 'total_invested', label: 'Total Invested', format: 'currency' },
      { field: 'margin_pct', label: 'Margin %', format: 'number' },
      { field: 'exception_reason', label: 'Exception', format: 'badge' },
    ],
    defaultFilters: [],
    defaultSortBy: 'margin_pct',
  },

  // ── Sales / Deals ──────────────────────────────────────────────────────────
  {
    id: 'sales-today',
    name: 'Deals Sold Today',
    description: "All deals marked sold today with salesperson, gross, and finance product totals.",
    category: 'sales',
    tags: ['sales', 'deals', 'today'],
    icon: 'CheckCircle',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'vehicle', label: 'Vehicle', format: 'text' },
      { field: 'salesperson', label: 'Salesperson', format: 'text' },
      { field: 'front_gross', label: 'Front Gross', format: 'currency' },
      { field: 'back_gross', label: 'Back Gross', format: 'currency' },
      { field: 'total_gross', label: 'Total Gross', format: 'currency' },
    ],
    defaultFilters: [
      { field: 'sale_date', operator: 'eq', value: 'today' },
      { field: 'status', operator: 'eq', value: 'Sold' },
    ],
    defaultSortBy: 'sale_date',
  },
  {
    id: 'sales-pending-delivery',
    name: 'Deals Pending Delivery',
    description: 'Sold deals awaiting vehicle delivery with scheduled delivery dates.',
    category: 'sales',
    tags: ['sales', 'deals', 'pending', 'delivery'],
    icon: 'Truck',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'vehicle', label: 'Vehicle', format: 'text' },
      { field: 'sale_date', label: 'Sale Date', format: 'date' },
      { field: 'delivery_date', label: 'Delivery Date', format: 'date' },
      { field: 'status', label: 'Status', format: 'badge' },
    ],
    defaultFilters: [{ field: 'status', operator: 'eq', value: 'Pending Delivery' }],
    defaultSortBy: 'delivery_date',
  },
  {
    id: 'sales-pending-funding',
    name: 'Deals Pending Funding',
    description: 'Delivered deals not yet funded by the lender with days-outstanding.',
    category: 'sales',
    tags: ['sales', 'deals', 'funding', 'back-office'],
    icon: 'Bank',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'delivery_date', label: 'Delivery Date', format: 'date' },
      { field: 'days_pending', label: 'Days Pending', format: 'number' },
      { field: 'deal_amount', label: 'Amount', format: 'currency' },
    ],
    defaultFilters: [{ field: 'status', operator: 'eq', value: 'Pending Funding' }],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'sales-unfunded-aging',
    name: 'Unfunded Deals Aging',
    description: 'Delivered and unfunded deals, grouped by aging bucket (7, 14, 21+ days).',
    category: 'sales',
    tags: ['sales', 'deals', 'aging', 'funding'],
    icon: 'HourglassHigh',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'days_pending', label: 'Days Pending', format: 'number' },
      { field: 'age_bucket', label: 'Age Bucket', format: 'badge' },
      { field: 'deal_amount', label: 'Amount', format: 'currency' },
    ],
    defaultFilters: [
      { field: 'status', operator: 'eq', value: 'Pending Funding' },
      { field: 'days_pending', operator: 'gte', value: 7 },
    ],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'sales-missing-stips',
    name: 'Missing Stips',
    description: 'Deals with outstanding stipulations required by the lender for funding.',
    category: 'sales',
    tags: ['sales', 'deals', 'stips', 'funding'],
    icon: 'FileMinus',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'missing_stips', label: 'Missing Stips', format: 'text' },
      { field: 'days_pending', label: 'Days Pending', format: 'number' },
    ],
    defaultFilters: [{ field: 'has_missing_stips', operator: 'eq', value: true }],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'sales-gross-performance',
    name: 'Gross/Deal Performance Summary',
    description: 'Front-end and back-end gross per deal with per-unit and total rollups.',
    category: 'sales',
    tags: ['sales', 'gross', 'performance'],
    icon: 'ChartLineUp',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'period', label: 'Period', format: 'text' },
      { field: 'units', label: 'Units', format: 'number' },
      { field: 'total_front', label: 'Total Front', format: 'currency' },
      { field: 'pvr_front', label: 'PVR Front', format: 'currency' },
      { field: 'total_back', label: 'Total Back', format: 'currency' },
      { field: 'pvr_back', label: 'PVR Back', format: 'currency' },
      { field: 'total_gross', label: 'Total Gross', format: 'currency' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'month_start' }],
    defaultGroupBy: 'period',
    defaultSortBy: 'period',
  },
  {
    id: 'sales-salesperson-performance',
    name: 'Salesperson Performance Summary',
    description: 'Units sold, gross, and closing ratio by salesperson for the selected period.',
    category: 'sales',
    tags: ['sales', 'salesperson', 'performance'],
    icon: 'UserCircle',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'salesperson', label: 'Salesperson', format: 'text' },
      { field: 'units', label: 'Units', format: 'number' },
      { field: 'total_gross', label: 'Total Gross', format: 'currency' },
      { field: 'avg_gross', label: 'Avg Gross', format: 'currency' },
      { field: 'leads', label: 'Leads', format: 'number' },
      { field: 'closing_ratio', label: 'Close %', format: 'number' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'month_start' }],
    defaultGroupBy: 'salesperson',
    defaultSortBy: 'total_gross',
  },
  {
    id: 'sales-fi-production',
    name: 'F&I Production Summary',
    description: 'Finance and insurance product penetration, PVR, and total reserve by period.',
    category: 'sales',
    tags: ['sales', 'fi', 'finance', 'insurance'],
    icon: 'Briefcase',
    dataSource: 'deals',
    defaultColumns: [
      { field: 'fi_manager', label: 'F&I Manager', format: 'text' },
      { field: 'deals', label: 'Deals', format: 'number' },
      { field: 'reserve', label: 'Reserve', format: 'currency' },
      { field: 'products_per_deal', label: 'Products/Deal', format: 'number' },
      { field: 'fi_pvr', label: 'F&I PVR', format: 'currency' },
      { field: 'warranty_pct', label: 'VSC %', format: 'number' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'month_start' }],
    defaultGroupBy: 'fi_manager',
    defaultSortBy: 'fi_pvr',
  },

  // ── Back Office ────────────────────────────────────────────────────────────
  {
    id: 'bo-title-pending',
    name: 'Title Pending',
    description: 'Deals with outstanding title work, grouped by days-pending and lender.',
    category: 'back_office',
    tags: ['back-office', 'title', 'pending'],
    icon: 'FileText',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'vehicle', label: 'Vehicle', format: 'text' },
      { field: 'sale_date', label: 'Sale Date', format: 'date' },
      { field: 'title_status', label: 'Title Status', format: 'badge' },
      { field: 'days_pending', label: 'Days', format: 'number' },
    ],
    defaultFilters: [{ field: 'title_status', operator: 'neq', value: 'Cleared' }],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'bo-registration-pending',
    name: 'Registration/Tag Pending',
    description: 'Sold units with open registration or tag/plate work pending at the DMV.',
    category: 'back_office',
    tags: ['back-office', 'registration', 'tags'],
    icon: 'IdentificationCard',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'vehicle', label: 'Vehicle', format: 'text' },
      { field: 'reg_status', label: 'Reg Status', format: 'badge' },
      { field: 'days_pending', label: 'Days', format: 'number' },
      { field: 'temp_tag_expiry', label: 'Temp Tag Exp', format: 'date' },
    ],
    defaultFilters: [{ field: 'reg_status', operator: 'neq', value: 'Complete' }],
    defaultSortBy: 'temp_tag_expiry',
  },
  {
    id: 'bo-payoff-pending',
    name: 'Payoff Pending',
    description: 'Trade-in vehicles where the prior lien payoff has not yet been confirmed.',
    category: 'back_office',
    tags: ['back-office', 'payoff', 'trades'],
    icon: 'Money',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'trade_vehicle', label: 'Trade Vehicle', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'payoff_amount', label: 'Payoff Amt', format: 'currency' },
      { field: 'days_pending', label: 'Days', format: 'number' },
    ],
    defaultFilters: [{ field: 'payoff_status', operator: 'neq', value: 'Confirmed' }],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'bo-accounting-exceptions',
    name: 'Accounting Exceptions',
    description: 'Deals with accounting discrepancies, reserve differences, or missing entries.',
    category: 'back_office',
    tags: ['back-office', 'accounting', 'exceptions'],
    icon: 'Calculator',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'exception_type', label: 'Exception', format: 'badge' },
      { field: 'amount', label: 'Amount', format: 'currency' },
      { field: 'assigned_to', label: 'Assigned To', format: 'text' },
      { field: 'days_open', label: 'Days Open', format: 'number' },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Resolved' }],
    defaultSortBy: 'days_open',
  },
  {
    id: 'bo-missing-docs',
    name: 'Missing Documents',
    description: 'Deals with incomplete document packages — missing signatures, IDs, or stipulations.',
    category: 'back_office',
    tags: ['back-office', 'documents', 'compliance'],
    icon: 'FolderMinus',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'missing_docs', label: 'Missing Docs', format: 'text' },
      { field: 'sale_date', label: 'Sale Date', format: 'date' },
      { field: 'days_open', label: 'Days Open', format: 'number' },
    ],
    defaultFilters: [{ field: 'has_missing_docs', operator: 'eq', value: true }],
    defaultSortBy: 'days_open',
  },
  {
    id: 'bo-ready-to-finalize',
    name: 'Ready to Finalize',
    description: 'Deals that have passed all checks and are ready for final booking.',
    category: 'back_office',
    tags: ['back-office', 'finalize', 'booking'],
    icon: 'Stamp',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'deal_number', label: 'Deal #', format: 'text' },
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'vehicle', label: 'Vehicle', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'deal_amount', label: 'Amount', format: 'currency' },
      { field: 'checklist_status', label: 'Checklist', format: 'badge' },
    ],
    defaultFilters: [{ field: 'finalize_ready', operator: 'eq', value: true }],
    defaultSortBy: 'deal_number',
  },

  // ── Fixed Ops / Recon ──────────────────────────────────────────────────────
  {
    id: 'fops-recon-queue',
    name: 'Recon Queue',
    description: 'All vehicles currently in the reconditioning pipeline with stage and elapsed time.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'recon', 'queue'],
    icon: 'Queue',
    dataSource: 'fixed_ops',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'recon_stage', label: 'Stage', format: 'badge' },
      { field: 'days_in_recon', label: 'Days In Recon', format: 'number' },
      { field: 'technician', label: 'Technician', format: 'text' },
      { field: 'estimated_complete', label: 'Est. Complete', format: 'date' },
    ],
    defaultFilters: [{ field: 'recon_status', operator: 'eq', value: 'In Progress' }],
    defaultSortBy: 'days_in_recon',
  },
  {
    id: 'fops-recon-spend',
    name: 'Recon Spend by Unit',
    description: 'Detailed recon cost breakdown per vehicle including parts, labor, and sublet.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'recon', 'cost', 'spend'],
    icon: 'Receipt',
    dataSource: 'fixed_ops',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'parts_cost', label: 'Parts', format: 'currency' },
      { field: 'labor_cost', label: 'Labor', format: 'currency' },
      { field: 'sublet_cost', label: 'Sublet', format: 'currency' },
      { field: 'total_recon', label: 'Total Recon', format: 'currency' },
    ],
    defaultFilters: [],
    defaultSortBy: 'total_recon',
  },
  {
    id: 'fops-open-issues',
    name: 'Open Vehicle Issues',
    description: 'Open mechanical or cosmetic issues on inventory units blocking front-line readiness.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'issues', 'recon'],
    icon: 'WarningDiamond',
    dataSource: 'fixed_ops',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'issue_type', label: 'Issue Type', format: 'badge' },
      { field: 'severity', label: 'Severity', format: 'badge' },
      { field: 'days_open', label: 'Days Open', format: 'number' },
      { field: 'assigned_tech', label: 'Assigned To', format: 'text' },
    ],
    defaultFilters: [{ field: 'issue_status', operator: 'eq', value: 'Open' }],
    defaultSortBy: 'days_open',
  },
  {
    id: 'fops-dealer-pack',
    name: 'Dealer Pack/Fuel/Soft Cost Summary',
    description: 'Breakdown of pack, fuel, and miscellaneous soft costs applied to inventory.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'pack', 'fuel', 'cost'],
    icon: 'GasPump',
    dataSource: 'fixed_ops',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'dealer_pack', label: 'Dealer Pack', format: 'currency' },
      { field: 'fuel_cost', label: 'Fuel', format: 'currency' },
      { field: 'soft_costs', label: 'Soft Costs', format: 'currency' },
      { field: 'total', label: 'Total', format: 'currency' },
    ],
    defaultFilters: [],
    defaultSortBy: 'total',
  },
  {
    id: 'fops-high-invested',
    name: 'High Invested Cost Units',
    description: 'Units where total investment exceeds threshold, at risk of negative gross.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'cost', 'risk', 'gross'],
    icon: 'ArrowFatLinesUp',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'total_invested', label: 'Total Invested', format: 'currency' },
      { field: 'list_price', label: 'List Price', format: 'currency' },
      { field: 'potential_gross', label: 'Potential Gross', format: 'currency' },
      { field: 'days_in_stock', label: 'Days', format: 'number' },
    ],
    defaultFilters: [{ field: 'total_invested', operator: 'gte', value: 15000 }],
    defaultSortBy: 'total_invested',
  },
  {
    id: 'fops-floor-plan',
    name: 'Floor Plan/Age Exposure',
    description: 'Estimated floor plan interest accrual and total carrying cost by aged inventory.',
    category: 'fixed_ops',
    tags: ['fixed-ops', 'floor-plan', 'aging', 'cost'],
    icon: 'CurrencyDollar',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'floored_amount', label: 'Floored Amt', format: 'currency' },
      { field: 'days_in_stock', label: 'Days', format: 'number' },
      { field: 'accrued_interest', label: 'Accrued Int.', format: 'currency' },
      { field: 'total_carrying', label: 'Total Carrying', format: 'currency' },
    ],
    defaultFilters: [{ field: 'is_floored', operator: 'eq', value: true }],
    defaultSortBy: 'total_carrying',
  },

  // ── Leads / CRM ────────────────────────────────────────────────────────────
  {
    id: 'crm-new-leads',
    name: 'New Leads by Day',
    description: 'Inbound leads grouped by day and source with assignment and response status.',
    category: 'leads_crm',
    tags: ['leads', 'crm', 'inbound'],
    icon: 'UserPlus',
    dataSource: 'leads',
    defaultColumns: [
      { field: 'date', label: 'Date', format: 'date' },
      { field: 'lead_count', label: 'Leads', format: 'number' },
      { field: 'source', label: 'Source', format: 'badge' },
      { field: 'assigned', label: 'Assigned', format: 'number' },
      { field: 'unassigned', label: 'Unassigned', format: 'number' },
      { field: 'responded', label: 'Responded', format: 'number' },
    ],
    defaultFilters: [{ field: 'date', operator: 'gte', value: 'week_start' }],
    defaultGroupBy: 'date',
    defaultSortBy: 'date',
  },
  {
    id: 'crm-follow-up-due',
    name: 'Follow-Up Due',
    description: 'Leads and customers with follow-up tasks due today or overdue.',
    category: 'leads_crm',
    tags: ['leads', 'crm', 'follow-up', 'tasks'],
    icon: 'BellRinging',
    dataSource: 'tasks',
    defaultColumns: [
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'contact_type', label: 'Type', format: 'badge' },
      { field: 'assigned_to', label: 'Assigned To', format: 'text' },
      { field: 'due_date', label: 'Due Date', format: 'date' },
      { field: 'days_overdue', label: 'Days Overdue', format: 'number' },
      { field: 'last_activity', label: 'Last Activity', format: 'date' },
    ],
    defaultFilters: [{ field: 'due_date', operator: 'lte', value: 'today' }],
    defaultSortBy: 'due_date',
  },
  {
    id: 'crm-stuck-leads',
    name: 'Leads Stuck Without Activity',
    description: 'Active leads with no logged activity in the past 3+ days.',
    category: 'leads_crm',
    tags: ['leads', 'crm', 'stuck', 'inactive'],
    icon: 'PauseCircle',
    dataSource: 'leads',
    defaultColumns: [
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'assigned_to', label: 'Salesperson', format: 'text' },
      { field: 'source', label: 'Source', format: 'badge' },
      { field: 'created_date', label: 'Created', format: 'date' },
      { field: 'days_no_activity', label: 'Days Inactive', format: 'number' },
      { field: 'last_activity', label: 'Last Activity', format: 'date' },
    ],
    defaultFilters: [{ field: 'days_no_activity', operator: 'gte', value: 3 }],
    defaultSortBy: 'days_no_activity',
  },
  {
    id: 'crm-credit-pipeline',
    name: 'Credit App Pipeline',
    description: 'Credit applications by status stage with lender, disposition, and aging.',
    category: 'leads_crm',
    tags: ['leads', 'crm', 'credit', 'pipeline'],
    icon: 'CreditCard',
    dataSource: 'credit_applications',
    defaultColumns: [
      { field: 'applicant_name', label: 'Applicant', format: 'text' },
      { field: 'lender', label: 'Lender', format: 'text' },
      { field: 'status', label: 'Status', format: 'badge' },
      { field: 'submitted_date', label: 'Submitted', format: 'date' },
      { field: 'days_pending', label: 'Days Pending', format: 'number' },
      { field: 'amount_requested', label: 'Amount', format: 'currency' },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Closed' }],
    defaultSortBy: 'days_pending',
  },
  {
    id: 'crm-customer-journey',
    name: 'Customer Journey Status',
    description: 'Full lifecycle view of active customers from lead through delivery.',
    category: 'leads_crm',
    tags: ['leads', 'crm', 'journey', 'lifecycle'],
    icon: 'Path',
    dataSource: 'leads',
    defaultColumns: [
      { field: 'customer_name', label: 'Customer', format: 'text' },
      { field: 'journey_stage', label: 'Stage', format: 'badge' },
      { field: 'assigned_to', label: 'Salesperson', format: 'text' },
      { field: 'days_in_stage', label: 'Days In Stage', format: 'number' },
      { field: 'next_step', label: 'Next Step', format: 'text' },
      { field: 'vehicle_interest', label: 'Vehicle Interest', format: 'text' },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Closed' }],
    defaultSortBy: 'days_in_stage',
  },

  // ── Digital / Marketing ────────────────────────────────────────────────────
  {
    id: 'dig-public-inventory-health',
    name: 'Public Inventory Health',
    description: 'Score of public-facing inventory quality including photos, price, and description.',
    category: 'digital_marketing',
    tags: ['digital', 'inventory', 'website', 'quality'],
    icon: 'Globe',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'health_score', label: 'Health Score', format: 'number' },
      { field: 'photo_count', label: 'Photos', format: 'number' },
      { field: 'has_description', label: 'Has Description', format: 'badge' },
      { field: 'is_listed', label: 'Listed Online', format: 'badge' },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Sold' }],
    defaultSortBy: 'health_score',
  },
  {
    id: 'dig-listing-quality',
    name: 'Website Listing Quality',
    description: 'Per-unit listing quality audit: title, photos, price, calls-to-action.',
    category: 'digital_marketing',
    tags: ['digital', 'website', 'listing', 'quality'],
    icon: 'MagnifyingGlass',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'listing_title', label: 'Title', format: 'text' },
      { field: 'photo_count', label: 'Photos', format: 'number' },
      { field: 'list_price', label: 'Price', format: 'currency' },
      { field: 'quality_flags', label: 'Quality Flags', format: 'badge' },
    ],
    defaultFilters: [],
    defaultSortBy: 'quality_flags',
  },
  {
    id: 'dig-missing-desc-images',
    name: 'Missing Description/Images',
    description: 'Active listings that are missing vehicle descriptions or have no images.',
    category: 'digital_marketing',
    tags: ['digital', 'description', 'images', 'quality'],
    icon: 'ImageBroken',
    dataSource: 'inventory',
    defaultColumns: [
      { field: 'stock_number', label: 'Stock #', format: 'text' },
      { field: 'year_make_model', label: 'Vehicle', format: 'text' },
      { field: 'has_description', label: 'Description', format: 'badge' },
      { field: 'photo_count', label: 'Photos', format: 'number' },
      { field: 'days_in_stock', label: 'Days In Stock', format: 'number' },
      { field: 'list_price', label: 'List Price', format: 'currency' },
    ],
    defaultFilters: [
      {
        field: 'has_description',
        operator: 'eq',
        value: false,
      },
    ],
    defaultSortBy: 'days_in_stock',
  },
  {
    id: 'dig-marketing-observations',
    name: 'Marketing Observation Summary',
    description: 'Logged marketing observations across website, ads, social, and inventory merchandising.',
    category: 'digital_marketing',
    tags: ['digital', 'marketing', 'observations'],
    icon: 'Eye',
    dataSource: 'back_office',
    defaultColumns: [
      { field: 'date_observed', label: 'Date', format: 'date' },
      { field: 'channel', label: 'Channel', format: 'badge' },
      { field: 'observation', label: 'Observation', format: 'text' },
      { field: 'severity', label: 'Severity', format: 'badge' },
      { field: 'status', label: 'Status', format: 'badge' },
    ],
    defaultFilters: [{ field: 'status', operator: 'neq', value: 'Resolved' }],
    defaultSortBy: 'date_observed',
  },
]

export const TEMPLATES_BY_CATEGORY = REPORT_TEMPLATES.reduce<
  Record<string, ReportTemplate[]>
>((acc, t) => {
  if (!acc[t.category]) acc[t.category] = []
  acc[t.category].push(t)
  return acc
}, {})
