/**
 * Deal Forms Printing System — template registry.
 *
 * Defines the canonical set of dealership form templates. Each template
 * specifies its sections, field definitions, and display metadata.
 * Adding a new form means adding a new entry here — no page-level logic needed.
 */
import type { DealFormTemplate, PacketPreset, FormFieldDef } from './dealForms.types'

// ---------------------------------------------------------------------------
// Helper factory
// ---------------------------------------------------------------------------

function field(
  id: string,
  label: string,
  dataKey: FormFieldDef['dataKey'],
  section: string,
  opts?: Partial<Pick<FormFieldDef, 'type' | 'required' | 'width' | 'helpText'>>
): FormFieldDef {
  return {
    id,
    label,
    dataKey,
    section,
    type: opts?.type ?? 'text',
    required: opts?.required ?? false,
    width: opts?.width ?? 'half',
    helpText: opts?.helpText,
  }
}

// ---------------------------------------------------------------------------
// Individual form templates
// ---------------------------------------------------------------------------

const buyersOrder: DealFormTemplate = {
  id: 'buyers-order',
  name: "Buyer's Order",
  shortName: "Buyer's Order",
  category: 'deal_documents',
  description: 'Primary purchase agreement showing vehicle, price, trade, and payment structure.',
  version: '1.0',
  printOrder: 1,
  sections: ['Dealer', 'Buyer', 'Vehicle', 'Trade', 'Financial Summary'],
  fields: [
    field('bo-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('bo-dealer-address', 'Dealer Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('bo-deal-number', 'Deal #', 'dealNumber', 'Dealer', { width: 'third' }),
    field('bo-deal-date', 'Deal Date', 'dealDate', 'Dealer', { type: 'date', width: 'third' }),
    field('bo-salesperson', 'Salesperson', 'salesperson', 'Dealer', { width: 'third' }),

    field('bo-buyer-name', 'Buyer Full Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('bo-buyer-address', 'Address', 'buyerAddress', 'Buyer', { width: 'half' }),
    field('bo-buyer-city', 'City', 'buyerCity', 'Buyer', { width: 'third' }),
    field('bo-buyer-state', 'State', 'buyerState', 'Buyer', { width: 'third' }),
    field('bo-buyer-zip', 'ZIP', 'buyerZip', 'Buyer', { width: 'third' }),
    field('bo-buyer-phone', 'Phone', 'buyerPhone', 'Buyer', { width: 'half' }),
    field('bo-buyer-email', 'Email', 'buyerEmail', 'Buyer', { width: 'half' }),
    field('bo-cobuyer-name', 'Co-Buyer Name', 'coBuyerFullName', 'Buyer', { width: 'full' }),

    field('bo-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('bo-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('bo-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('bo-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('bo-trim', 'Trim', 'vehicleTrim', 'Vehicle', { width: 'half' }),
    field('bo-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('bo-mileage', 'Mileage', 'vehicleMileage', 'Vehicle', { type: 'number', width: 'half' }),
    field('bo-color', 'Color', 'vehicleColor', 'Vehicle', { width: 'half' }),

    field('bo-trade-year', 'Trade Year', 'tradeYear', 'Trade', { width: 'third' }),
    field('bo-trade-make', 'Trade Make', 'tradeMake', 'Trade', { width: 'third' }),
    field('bo-trade-model', 'Trade Model', 'tradeModel', 'Trade', { width: 'third' }),
    field('bo-trade-vin', 'Trade VIN', 'tradeVIN', 'Trade', { width: 'half' }),
    field('bo-trade-allowance', 'Trade Allowance', 'tradeAllowance', 'Trade', { type: 'currency', width: 'half' }),
    field('bo-trade-payoff', 'Trade Payoff', 'tradePayoff', 'Trade', { type: 'currency', width: 'half' }),
    field('bo-net-trade', 'Net Trade Value', 'netTradeValue', 'Trade', { type: 'currency', width: 'half' }),

    field('bo-sale-price', 'Sale Price', 'salePrice', 'Financial Summary', { type: 'currency', required: true, width: 'half' }),
    field('bo-down-payment', 'Down Payment', 'downPayment', 'Financial Summary', { type: 'currency', width: 'half' }),
    field('bo-taxes', 'Taxes', 'taxesAmount', 'Financial Summary', { type: 'currency', width: 'half' }),
    field('bo-fees', 'Fees', 'feesAmount', 'Financial Summary', { type: 'currency', width: 'half' }),
    field('bo-total', 'Total Amount Due', 'totalAmountDue', 'Financial Summary', { type: 'currency', width: 'full' }),
  ],
}

const retailPurchaseAgreement: DealFormTemplate = {
  id: 'retail-purchase-agreement',
  name: 'Retail Purchase Agreement',
  shortName: 'Retail Agreement',
  category: 'deal_documents',
  description: 'Formal retail purchase agreement for signed deals.',
  version: '1.0',
  printOrder: 2,
  sections: ['Parties', 'Vehicle', 'Terms'],
  fields: [
    field('rpa-dealer-name', 'Dealer Name', 'dealerName', 'Parties', { required: true, width: 'half' }),
    field('rpa-dealer-lic', 'Dealer License', 'dealerLicenseNumber', 'Parties', { width: 'half' }),
    field('rpa-buyer-name', 'Buyer Full Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('rpa-cobuyer-name', 'Co-Buyer Name', 'coBuyerFullName', 'Parties', { width: 'half' }),
    field('rpa-buyer-address', 'Buyer Address', 'buyerAddress', 'Parties', { width: 'full' }),
    field('rpa-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('rpa-vehicle-desc', 'Vehicle Description', 'vehicleDescription', 'Vehicle', { width: 'full' }),
    field('rpa-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('rpa-mileage', 'Mileage', 'vehicleMileage', 'Vehicle', { type: 'number', width: 'half' }),
    field('rpa-sale-price', 'Purchase Price', 'salePrice', 'Terms', { type: 'currency', required: true, width: 'half' }),
    field('rpa-deal-type', 'Deal Type', 'dealType', 'Terms', { width: 'half' }),
    field('rpa-sale-date', 'Sale Date', 'saleDate', 'Terms', { type: 'date', width: 'half' }),
    field('rpa-salesperson', 'Salesperson', 'salesperson', 'Terms', { width: 'half' }),
    field('rpa-fi-manager', 'F&I Manager', 'fiManager', 'Terms', { width: 'half' }),
  ],
}

const creditApplicationPrintout: DealFormTemplate = {
  id: 'credit-application-printout',
  name: 'Credit Application Printout',
  shortName: 'Credit App',
  category: 'credit_finance',
  description: 'Printed copy of the completed credit application for signatures.',
  version: '1.0',
  printOrder: 5,
  sections: ['Applicant', 'Employment', 'Residence', 'Co-Applicant'],
  fields: [
    field('cap-buyer-name', 'Applicant Full Name', 'buyerFullName', 'Applicant', { required: true, width: 'half' }),
    field('cap-buyer-dob', 'Date of Birth', 'buyerDOB', 'Applicant', { type: 'date', width: 'half' }),
    field('cap-buyer-ssn', 'SSN (Last 4)', 'buyerSSNMasked', 'Applicant', { type: 'masked', width: 'third' }),
    field('cap-buyer-dl', "Driver's License #", 'buyerDLNumber', 'Applicant', { width: 'third' }),
    field('cap-buyer-dl-state', 'DL State', 'buyerDLState', 'Applicant', { width: 'third' }),
    field('cap-buyer-phone', 'Phone', 'buyerPhone', 'Applicant', { width: 'half' }),
    field('cap-buyer-email', 'Email', 'buyerEmail', 'Applicant', { width: 'half' }),
    field('cap-buyer-address', 'Current Address', 'buyerAddress', 'Residence', { width: 'full' }),
    field('cap-buyer-city', 'City', 'buyerCity', 'Residence', { width: 'third' }),
    field('cap-buyer-state', 'State', 'buyerState', 'Residence', { width: 'third' }),
    field('cap-buyer-zip', 'ZIP', 'buyerZip', 'Residence', { width: 'third' }),
    field('cap-buyer-housing', 'Housing Status', 'buyerHousingStatus', 'Residence', { width: 'half' }),
    field('cap-buyer-housing-pmt', 'Monthly Housing Payment', 'buyerMonthlyHousing', 'Residence', { type: 'currency', width: 'half' }),
    field('cap-employer', 'Employer Name', 'buyerEmployer', 'Employment', { width: 'half' }),
    field('cap-occupation', 'Occupation', 'buyerOccupation', 'Employment', { width: 'half' }),
    field('cap-income', 'Gross Monthly Income', 'buyerMonthlyIncome', 'Employment', { type: 'currency', width: 'half' }),
    field('cap-cobuyer-name', 'Co-Applicant Name', 'coBuyerFullName', 'Co-Applicant', { width: 'half' }),
    field('cap-cobuyer-dob', 'Co-Applicant DOB', 'coBuyerDOB', 'Co-Applicant', { type: 'date', width: 'half' }),
    field('cap-cobuyer-employer', 'Co-Applicant Employer', 'coBuyerEmployer', 'Co-Applicant', { width: 'half' }),
    field('cap-cobuyer-income', 'Co-Applicant Income', 'coBuyerMonthlyIncome', 'Co-Applicant', { type: 'currency', width: 'half' }),
  ],
}

const dealRecap: DealFormTemplate = {
  id: 'deal-recap',
  name: 'Deal Recap',
  shortName: 'Deal Recap',
  category: 'deal_documents',
  description: 'Summary of all deal numbers for manager and F&I review.',
  version: '1.0',
  printOrder: 3,
  sections: ['Deal Info', 'Buyer', 'Vehicle', 'Structure', 'Lender'],
  fields: [
    field('dr-deal-number', 'Deal #', 'dealNumber', 'Deal Info', { width: 'third' }),
    field('dr-deal-date', 'Deal Date', 'dealDate', 'Deal Info', { type: 'date', width: 'third' }),
    field('dr-deal-type', 'Deal Type', 'dealType', 'Deal Info', { width: 'third' }),
    field('dr-salesperson', 'Salesperson', 'salesperson', 'Deal Info', { width: 'half' }),
    field('dr-fi-manager', 'F&I Manager', 'fiManager', 'Deal Info', { width: 'half' }),
    field('dr-buyer', 'Buyer', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('dr-cobuyer', 'Co-Buyer', 'coBuyerFullName', 'Buyer', { width: 'half' }),
    field('dr-vin', 'VIN', 'vehicleVIN', 'Vehicle', { width: 'full' }),
    field('dr-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('dr-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('dr-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('dr-sale-price', 'Sale Price', 'salePrice', 'Structure', { type: 'currency', required: true, width: 'third' }),
    field('dr-down', 'Down Payment', 'downPayment', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-trade-allowance', 'Trade Allowance', 'tradeAllowance', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-trade-payoff', 'Trade Payoff', 'tradePayoff', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-taxes', 'Taxes', 'taxesAmount', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-fees', 'Fees', 'feesAmount', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-amount-financed', 'Amount Financed', 'amountFinanced', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-term', 'Term (Months)', 'termMonths', 'Structure', { type: 'number', width: 'third' }),
    field('dr-apr', 'APR', 'apr', 'Structure', { width: 'third' }),
    field('dr-payment', 'Monthly Payment', 'monthlyPayment', 'Structure', { type: 'currency', width: 'third' }),
    field('dr-lender', 'Lender', 'lenderName', 'Lender', { width: 'half' }),
    field('dr-lender-status', 'Decision Status', 'lenderDecisionStatus', 'Lender', { width: 'half' }),
  ],
}

const tradeAppraisalWorksheet: DealFormTemplate = {
  id: 'trade-appraisal-worksheet',
  name: 'Trade Appraisal / Trade Worksheet',
  shortName: 'Trade Worksheet',
  category: 'trade',
  description: "Appraisal worksheet for the customer's trade-in vehicle.",
  version: '1.0',
  printOrder: 10,
  sections: ['Customer', 'Trade Vehicle', 'Appraisal Values'],
  fields: [
    field('ta-buyer-name', 'Customer Name', 'buyerFullName', 'Customer', { required: true, width: 'half' }),
    field('ta-date', 'Appraisal Date', 'dealDate', 'Customer', { type: 'date', width: 'half' }),
    field('ta-year', 'Year', 'tradeYear', 'Trade Vehicle', { required: true, width: 'third' }),
    field('ta-make', 'Make', 'tradeMake', 'Trade Vehicle', { required: true, width: 'third' }),
    field('ta-model', 'Model', 'tradeModel', 'Trade Vehicle', { required: true, width: 'third' }),
    field('ta-trim', 'Trim', 'tradeTrim', 'Trade Vehicle', { width: 'third' }),
    field('ta-vin', 'VIN', 'tradeVIN', 'Trade Vehicle', { width: 'two-thirds' }),
    field('ta-mileage', 'Mileage', 'tradeMileage', 'Trade Vehicle', { type: 'number', width: 'half' }),
    field('ta-condition', 'Condition Notes', 'tradeConditionNotes', 'Trade Vehicle', { type: 'textarea', width: 'full' }),
    field('ta-acv', 'Actual Cash Value (ACV)', 'tradeACV', 'Appraisal Values', { type: 'currency', width: 'half' }),
    field('ta-allowance', 'Trade Allowance', 'tradeAllowance', 'Appraisal Values', { type: 'currency', width: 'half' }),
    field('ta-payoff', 'Payoff Amount', 'tradePayoff', 'Appraisal Values', { type: 'currency', width: 'half' }),
    field('ta-net-trade', 'Net Trade Value', 'netTradeValue', 'Appraisal Values', { type: 'currency', width: 'half' }),
    field('ta-payoff-lender', 'Payoff Lender', 'tradePayoffLender', 'Appraisal Values', { width: 'full' }),
  ],
}

const privacyNotice: DealFormTemplate = {
  id: 'privacy-notice',
  name: 'Privacy Notice',
  shortName: 'Privacy Notice',
  category: 'disclosure',
  description: 'Gramm-Leach-Bliley Act privacy disclosure for the customer.',
  version: '1.0',
  printOrder: 20,
  sections: ['Parties'],
  fields: [
    field('pn-dealer-name', 'Dealer Name', 'dealerName', 'Parties', { required: true, width: 'half' }),
    field('pn-buyer-name', 'Customer Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('pn-date', 'Date', 'dealDate', 'Parties', { type: 'date', width: 'half' }),
    field('pn-buyer-address', 'Customer Address', 'buyerAddress', 'Parties', { width: 'half' }),
  ],
}

const odometerStatement: DealFormTemplate = {
  id: 'odometer-statement',
  name: 'Odometer Disclosure Statement',
  shortName: 'Odometer Disclosure',
  category: 'disclosure',
  description: 'Federal odometer disclosure as required by TIMA.',
  version: '1.0',
  printOrder: 21,
  sections: ['Vehicle', 'Parties'],
  fields: [
    field('od-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('od-year', 'Year', 'vehicleYear', 'Vehicle', { required: true, width: 'third' }),
    field('od-make', 'Make', 'vehicleMake', 'Vehicle', { required: true, width: 'third' }),
    field('od-model', 'Model', 'vehicleModel', 'Vehicle', { required: true, width: 'third' }),
    field('od-mileage', 'Odometer Reading', 'vehicleMileage', 'Vehicle', { type: 'number', required: true, width: 'half' }),
    field('od-buyer', 'Buyer Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('od-dealer', 'Selling Dealer', 'dealerName', 'Parties', { required: true, width: 'half' }),
    field('od-date', 'Transfer Date', 'deliveryDate', 'Parties', { type: 'date', width: 'half' }),
  ],
}

const arbitrationAcknowledgment: DealFormTemplate = {
  id: 'arbitration-acknowledgment',
  name: 'Arbitration / Delivery Acknowledgment',
  shortName: 'Delivery Ack',
  category: 'delivery',
  description: 'Customer acknowledgment of arbitration agreement and vehicle delivery.',
  version: '1.0',
  printOrder: 22,
  sections: ['Parties', 'Vehicle', 'Delivery'],
  fields: [
    field('aa-buyer', 'Buyer Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('aa-cobuyer', 'Co-Buyer Name', 'coBuyerFullName', 'Parties', { width: 'half' }),
    field('aa-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('aa-vehicle', 'Vehicle Description', 'vehicleDescription', 'Vehicle', { width: 'full' }),
    field('aa-delivery-date', 'Delivery Date', 'deliveryDate', 'Delivery', { type: 'date', required: true, width: 'half' }),
    field('aa-dealer', 'Dealer Name', 'dealerName', 'Delivery', { required: true, width: 'half' }),
  ],
}

const weOwe: DealFormTemplate = {
  id: 'we-owe',
  name: 'We Owe / Due Bill',
  shortName: 'We Owe',
  category: 'delivery',
  description: 'Records items the dealership owes the customer after delivery.',
  version: '1.0',
  printOrder: 25,
  sections: ['Parties', 'Vehicle', 'Items Owed'],
  fields: [
    field('wo-dealer', 'Dealer Name', 'dealerName', 'Parties', { required: true, width: 'half' }),
    field('wo-buyer', 'Buyer Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('wo-vin', 'VIN', 'vehicleVIN', 'Vehicle', { width: 'full' }),
    field('wo-vehicle', 'Vehicle', 'vehicleDescription', 'Vehicle', { width: 'full' }),
    field('wo-sale-date', 'Sale Date', 'saleDate', 'Parties', { type: 'date', width: 'half' }),
    field('wo-delivery-date', 'Delivery Date', 'deliveryDate', 'Parties', { type: 'date', width: 'half' }),
  ],
}

const fundingLenderCoverSheet: DealFormTemplate = {
  id: 'funding-lender-cover-sheet',
  name: 'Funding / Lender Cover Sheet',
  shortName: 'Lender Cover',
  category: 'credit_finance',
  description: 'Cover sheet submitted with funding package to lender.',
  version: '1.0',
  printOrder: 6,
  showForDealTypes: ['retail_finance'],
  sections: ['Lender', 'Deal', 'Vehicle', 'Buyer'],
  fields: [
    field('fl-lender', 'Lender Name', 'lenderName', 'Lender', { required: true, width: 'half' }),
    field('fl-lender-address', 'Lender Address', 'lenderAddress', 'Lender', { width: 'half' }),
    field('fl-dealer', 'Dealer Name', 'dealerName', 'Lender', { required: true, width: 'half' }),
    field('fl-dealer-phone', 'Dealer Phone', 'dealerPhone', 'Lender', { width: 'half' }),
    field('fl-deal-number', 'Deal #', 'dealNumber', 'Deal', { width: 'third' }),
    field('fl-deal-date', 'Deal Date', 'dealDate', 'Deal', { type: 'date', width: 'third' }),
    field('fl-deal-type', 'Deal Type', 'dealType', 'Deal', { width: 'third' }),
    field('fl-amount-financed', 'Amount Financed', 'amountFinanced', 'Deal', { type: 'currency', required: true, width: 'third' }),
    field('fl-apr', 'APR', 'apr', 'Deal', { width: 'third' }),
    field('fl-term', 'Term', 'termMonths', 'Deal', { type: 'number', width: 'third' }),
    field('fl-monthly-payment', 'Monthly Payment', 'monthlyPayment', 'Deal', { type: 'currency', width: 'half' }),
    field('fl-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('fl-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('fl-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('fl-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('fl-buyer', 'Buyer Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('fl-cobuyer', 'Co-Buyer Name', 'coBuyerFullName', 'Buyer', { width: 'half' }),
  ],
}

const titleRegistrationWorksheet: DealFormTemplate = {
  id: 'title-registration-worksheet',
  name: 'Title / Registration Worksheet',
  shortName: 'Title Worksheet',
  category: 'title_registration',
  description: 'Internal worksheet for title processing and registration.',
  version: '1.0',
  printOrder: 30,
  sections: ['Vehicle', 'Buyer', 'Title Info'],
  fields: [
    field('tr-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('tr-year', 'Year', 'vehicleYear', 'Vehicle', { required: true, width: 'third' }),
    field('tr-make', 'Make', 'vehicleMake', 'Vehicle', { required: true, width: 'third' }),
    field('tr-model', 'Model', 'vehicleModel', 'Vehicle', { required: true, width: 'third' }),
    field('tr-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('tr-mileage', 'Mileage', 'vehicleMileage', 'Vehicle', { type: 'number', width: 'half' }),
    field('tr-buyer', 'Registered Owner', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('tr-cobuyer', 'Co-Owner', 'coBuyerFullName', 'Buyer', { width: 'half' }),
    field('tr-buyer-address', 'Registration Address', 'buyerAddress', 'Buyer', { width: 'full' }),
    field('tr-city', 'City', 'buyerCity', 'Buyer', { width: 'third' }),
    field('tr-state', 'State', 'buyerState', 'Buyer', { width: 'third' }),
    field('tr-zip', 'ZIP', 'buyerZip', 'Buyer', { width: 'third' }),
    field('tr-sale-price', 'Sale Price', 'salePrice', 'Title Info', { type: 'currency', width: 'half' }),
    field('tr-sale-date', 'Sale Date', 'saleDate', 'Title Info', { type: 'date', width: 'half' }),
    field('tr-lender', 'Lienholder', 'lenderName', 'Title Info', { width: 'full' }),
    field('tr-dealer', 'Selling Dealer', 'dealerName', 'Title Info', { required: true, width: 'half' }),
    field('tr-dealer-lic', 'Dealer License', 'dealerLicenseNumber', 'Title Info', { width: 'half' }),
  ],
}

const buyerInformationSheet: DealFormTemplate = {
  id: 'buyer-information-sheet',
  name: 'Buyer Information Sheet',
  shortName: 'Buyer Info',
  category: 'buyer_information',
  description: 'Full buyer profile used for deal file and F&I records.',
  version: '1.0',
  printOrder: 4,
  sections: ['Buyer Identity', 'Contact', 'Employment & Income'],
  fields: [
    field('bi-full-name', 'Full Legal Name', 'buyerFullName', 'Buyer Identity', { required: true, width: 'half' }),
    field('bi-dob', 'Date of Birth', 'buyerDOB', 'Buyer Identity', { type: 'date', width: 'half' }),
    field('bi-dl', "Driver's License #", 'buyerDLNumber', 'Buyer Identity', { width: 'half' }),
    field('bi-dl-state', 'DL State', 'buyerDLState', 'Buyer Identity', { width: 'half' }),
    field('bi-ssn-masked', 'SSN (Last 4)', 'buyerSSNMasked', 'Buyer Identity', { type: 'masked', width: 'half' }),
    field('bi-address', 'Address', 'buyerAddress', 'Contact', { width: 'full' }),
    field('bi-city', 'City', 'buyerCity', 'Contact', { width: 'third' }),
    field('bi-state', 'State', 'buyerState', 'Contact', { width: 'third' }),
    field('bi-zip', 'ZIP', 'buyerZip', 'Contact', { width: 'third' }),
    field('bi-phone', 'Phone', 'buyerPhone', 'Contact', { width: 'half' }),
    field('bi-email', 'Email', 'buyerEmail', 'Contact', { width: 'half' }),
    field('bi-housing', 'Housing Status', 'buyerHousingStatus', 'Employment & Income', { width: 'half' }),
    field('bi-housing-pmt', 'Monthly Housing', 'buyerMonthlyHousing', 'Employment & Income', { type: 'currency', width: 'half' }),
    field('bi-employer', 'Employer', 'buyerEmployer', 'Employment & Income', { width: 'half' }),
    field('bi-occupation', 'Occupation', 'buyerOccupation', 'Employment & Income', { width: 'half' }),
    field('bi-income', 'Gross Monthly Income', 'buyerMonthlyIncome', 'Employment & Income', { type: 'currency', width: 'half' }),
  ],
}

const coBuyerInformationSheet: DealFormTemplate = {
  id: 'cobuyer-information-sheet',
  name: 'Co-Buyer Information Sheet',
  shortName: 'Co-Buyer Info',
  category: 'buyer_information',
  description: 'Full co-buyer/joint applicant profile.',
  version: '1.0',
  printOrder: 5,
  sections: ['Co-Buyer Identity', 'Contact', 'Employment & Income'],
  fields: [
    field('cb-full-name', 'Co-Buyer Full Name', 'coBuyerFullName', 'Co-Buyer Identity', { required: true, width: 'half' }),
    field('cb-dob', 'Date of Birth', 'coBuyerDOB', 'Co-Buyer Identity', { type: 'date', width: 'half' }),
    field('cb-dl', "Driver's License #", 'coBuyerDLNumber', 'Co-Buyer Identity', { width: 'half' }),
    field('cb-ssn', 'SSN (Last 4)', 'coBuyerSSNMasked', 'Co-Buyer Identity', { type: 'masked', width: 'half' }),
    field('cb-address', 'Address', 'coBuyerAddress', 'Contact', { width: 'full' }),
    field('cb-city', 'City', 'coBuyerCity', 'Contact', { width: 'third' }),
    field('cb-state', 'State', 'coBuyerState', 'Contact', { width: 'third' }),
    field('cb-zip', 'ZIP', 'coBuyerZip', 'Contact', { width: 'third' }),
    field('cb-phone', 'Phone', 'coBuyerPhone', 'Contact', { width: 'half' }),
    field('cb-email', 'Email', 'coBuyerEmail', 'Contact', { width: 'half' }),
    field('cb-employer', 'Employer', 'coBuyerEmployer', 'Employment & Income', { width: 'half' }),
    field('cb-income', 'Gross Monthly Income', 'coBuyerMonthlyIncome', 'Employment & Income', { type: 'currency', width: 'half' }),
  ],
}

const insuranceVerification: DealFormTemplate = {
  id: 'insurance-verification',
  name: 'Insurance Verification Form',
  shortName: 'Insurance Verify',
  category: 'delivery',
  description: 'Records proof-of-insurance at time of delivery.',
  version: '1.0',
  printOrder: 26,
  sections: ['Vehicle', 'Buyer', 'Insurance'],
  fields: [
    field('iv-buyer', 'Buyer Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('iv-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'full' }),
    field('iv-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('iv-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('iv-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('iv-delivery-date', 'Delivery Date', 'deliveryDate', 'Insurance', { type: 'date', width: 'half' }),
  ],
}

// ---------------------------------------------------------------------------
// NCM-style form templates
// ---------------------------------------------------------------------------

const vehicleEquipmentCondition: DealFormTemplate = {
  id: 'vehicle-equipment-condition',
  name: 'Vehicle Equipment / Condition Form',
  shortName: 'Equipment / Condition',
  category: 'delivery',
  description: 'Documents vehicle equipment present and overall condition at time of sale.',
  version: '1.0',
  printOrder: 27,
  sections: ['Vehicle', 'Equipment Checklist', 'Condition Notes', 'Parties'],
  fields: [
    field('vec-year', 'Year', 'vehicleYear', 'Vehicle', { required: true, width: 'third' }),
    field('vec-make', 'Make', 'vehicleMake', 'Vehicle', { required: true, width: 'third' }),
    field('vec-model', 'Model', 'vehicleModel', 'Vehicle', { required: true, width: 'third' }),
    field('vec-vin', 'VIN', 'vehicleVIN', 'Vehicle', { width: 'two-thirds' }),
    field('vec-vin-last6', 'VIN Last 6', 'vehicleVINLast6', 'Vehicle', { width: 'third' }),
    field('vec-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('vec-mileage', 'Mileage', 'vehicleMileage', 'Vehicle', { type: 'number', width: 'half' }),
    field('vec-ac', 'Air Conditioning', 'equipAC', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-heat', 'Heat / Defrost', 'equipHeat', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-radio', 'AM/FM Radio', 'equipRadio', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-cd', 'CD / Media Player', 'equipCDPlayer', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-power', 'Power Windows / Locks', 'equipPower', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-cruise', 'Cruise Control', 'equipCruise', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-tilt', 'Tilt Steering Wheel', 'equipTiltWheel', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-sunroof', 'Sunroof / Moonroof', 'equipSunroof', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-leather', 'Leather Seats', 'equipLeather', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-alloy', 'Alloy / Aluminum Wheels', 'equipAlloyWheels', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-defrost', 'Rear Window Defrost', 'equipRearDefrost', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-abs', 'ABS Brakes', 'equipABS', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-airbag', 'Airbags', 'equipAirbag', 'Equipment Checklist', { type: 'checkbox', width: 'half' }),
    field('vec-notes', 'Condition / Notes', 'vehicleEquipmentNotes', 'Condition Notes', { type: 'textarea', width: 'full' }),
    field('vec-buyer', 'Buyer Name', 'buyerFullName', 'Parties', { required: true, width: 'half' }),
    field('vec-date', 'Date', 'dealDate', 'Parties', { type: 'date', width: 'half' }),
    field('vec-dealer', 'Dealer Name', 'dealerName', 'Parties', { width: 'half' }),
    field('vec-salesperson', 'Salesperson', 'salesperson', 'Parties', { width: 'half' }),
  ],
}

const checkRequest: DealFormTemplate = {
  id: 'check-request',
  name: 'Check Request Form',
  shortName: 'Check Request',
  category: 'deal_documents',
  description: 'Internal check request for dealership disbursements (payoffs, lien releases, refunds, etc.).',
  version: '1.0',
  printOrder: 50,
  sections: ['Dealer', 'Request Details', 'Authorization'],
  fields: [
    field('cr-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('cr-dealer-address', 'Dealer Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('cr-dealer-phone', 'Dealer Phone', 'dealerPhone', 'Dealer', { width: 'half' }),
    field('cr-dealer-fax', 'Dealer Fax', 'dealerFax', 'Dealer', { width: 'half' }),
    field('cr-date', 'Request Date', 'checkRequestDate', 'Request Details', { type: 'date', required: true, width: 'third' }),
    field('cr-deal-number', 'Deal #', 'dealNumber', 'Request Details', { width: 'third' }),
    field('cr-buyer', 'Customer Name', 'buyerFullName', 'Request Details', { width: 'third' }),
    field('cr-payee', 'Pay To (Payee)', 'checkRequestPayee', 'Request Details', { required: true, width: 'full' }),
    field('cr-amount', 'Amount', 'checkRequestAmount', 'Request Details', { type: 'currency', required: true, width: 'half' }),
    field('cr-reason', 'Reason / Description', 'checkRequestReason', 'Request Details', { type: 'textarea', required: true, width: 'full' }),
    field('cr-vehicle', 'Vehicle Description', 'vehicleDescription', 'Request Details', { width: 'full' }),
    field('cr-vin', 'VIN', 'vehicleVIN', 'Request Details', { width: 'half' }),
    field('cr-stock', 'Stock #', 'vehicleStockNumber', 'Request Details', { width: 'half' }),
    field('cr-authorized-by', 'Authorized By', 'checkRequestAuthorizedBy', 'Authorization', { required: true, width: 'half' }),
    field('cr-salesperson', 'Salesperson', 'salesperson', 'Authorization', { width: 'half' }),
  ],
}

const paymentAgreement: DealFormTemplate = {
  id: 'payment-agreement',
  name: 'Payment Agreement Form',
  shortName: 'Payment Agreement',
  category: 'deal_documents',
  description: 'Records agreed payment terms between buyer and dealership.',
  version: '1.0',
  printOrder: 8,
  sections: ['Dealer', 'Buyer', 'Vehicle', 'Payment Terms'],
  fields: [
    field('pa-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('pa-dealer-address', 'Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('pa-dealer-city', 'City', 'dealerCity', 'Dealer', { width: 'third' }),
    field('pa-dealer-state', 'State', 'dealerState', 'Dealer', { width: 'third' }),
    field('pa-dealer-zip', 'ZIP', 'dealerZip', 'Dealer', { width: 'third' }),
    field('pa-dealer-phone', 'Phone', 'dealerPhone', 'Dealer', { width: 'half' }),
    field('pa-buyer-name', 'Buyer Full Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('pa-buyer-address', 'Address', 'buyerAddress', 'Buyer', { width: 'half' }),
    field('pa-buyer-city', 'City', 'buyerCity', 'Buyer', { width: 'third' }),
    field('pa-buyer-state', 'State', 'buyerState', 'Buyer', { width: 'third' }),
    field('pa-buyer-zip', 'ZIP', 'buyerZip', 'Buyer', { width: 'third' }),
    field('pa-buyer-phone', 'Phone', 'buyerPhone', 'Buyer', { width: 'half' }),
    field('pa-cobuyer', 'Co-Buyer Name', 'coBuyerFullName', 'Buyer', { width: 'half' }),
    field('pa-vin', 'VIN', 'vehicleVIN', 'Vehicle', { width: 'full' }),
    field('pa-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('pa-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('pa-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('pa-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('pa-sale-price', 'Sale Price', 'salePrice', 'Payment Terms', { type: 'currency', required: true, width: 'half' }),
    field('pa-down-payment', 'Down Payment', 'downPayment', 'Payment Terms', { type: 'currency', width: 'half' }),
    field('pa-payment-amount', 'Payment Amount', 'paymentAmount', 'Payment Terms', { type: 'currency', required: true, width: 'half' }),
    field('pa-payment-due', 'Payment Due Date', 'paymentDueDate', 'Payment Terms', { type: 'date', required: true, width: 'half' }),
    field('pa-payment-method', 'Payment Method', 'paymentMethod', 'Payment Terms', { width: 'half' }),
    field('pa-deal-date', 'Deal Date', 'dealDate', 'Payment Terms', { type: 'date', width: 'half' }),
    field('pa-salesperson', 'Salesperson', 'salesperson', 'Payment Terms', { width: 'half' }),
  ],
}

const fourSquareWorksheet: DealFormTemplate = {
  id: 'four-square-worksheet',
  name: 'Four Square / "Today Only Let\'s Make A Deal" Worksheet',
  shortName: 'Four Square',
  category: 'deal_documents',
  description: 'Classic four-box deal worksheet showing vehicle price, trade, down payment, and monthly payment.',
  version: '1.0',
  printOrder: 7,
  sections: ['Dealer', 'Vehicle', 'Buyer', 'Deal Structure'],
  fields: [
    field('fs-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('fs-dealer-address', 'Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('fs-dealer-phone', 'Phone', 'dealerPhone', 'Dealer', { width: 'half' }),
    field('fs-date', 'Date', 'dealDate', 'Dealer', { type: 'date', width: 'half' }),
    field('fs-year', 'Year', 'vehicleYear', 'Vehicle', { required: true, width: 'third' }),
    field('fs-make', 'Make', 'vehicleMake', 'Vehicle', { required: true, width: 'third' }),
    field('fs-model', 'Model', 'vehicleModel', 'Vehicle', { required: true, width: 'third' }),
    field('fs-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'half' }),
    field('fs-vin-last6', 'VIN Last 6', 'vehicleVINLast6', 'Vehicle', { width: 'half' }),
    field('fs-buyer', 'Buyer Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('fs-buyer-phone', 'Phone', 'buyerPhone', 'Buyer', { width: 'half' }),
    field('fs-ask-price', 'Box 1 — Asking Price', 'fourSquareAskPrice', 'Deal Structure', { type: 'currency', required: true, width: 'half', helpText: 'Vehicle asking / sale price' }),
    field('fs-trade-value', 'Box 2 — Trade Value', 'fourSquareTradeValue', 'Deal Structure', { type: 'currency', width: 'half', helpText: 'Trade-in allowance offered' }),
    field('fs-down-payment', 'Box 3 — Down Payment', 'fourSquareDownPayment', 'Deal Structure', { type: 'currency', width: 'half', helpText: 'Cash / draft down required' }),
    field('fs-monthly-payment', 'Box 4 — Monthly Payment', 'fourSquareMonthlyPayment', 'Deal Structure', { type: 'currency', width: 'half', helpText: 'Estimated monthly payment' }),
    field('fs-salesperson', 'Salesperson', 'salesperson', 'Deal Structure', { width: 'half' }),
    field('fs-sales-manager', 'Sales Manager', 'salesManager', 'Deal Structure', { width: 'half' }),
  ],
}

const downPaymentReceipt: DealFormTemplate = {
  id: 'down-payment-receipt',
  name: 'Down Payment Receipt / Acknowledgment',
  shortName: 'Down Pmt Receipt',
  category: 'deal_documents',
  description: 'Acknowledges receipt of a down payment or deposit from the buyer.',
  version: '1.0',
  printOrder: 9,
  sections: ['Dealer', 'Buyer', 'Vehicle', 'Receipt Details'],
  fields: [
    field('dp-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('dp-dealer-address', 'Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('dp-dealer-city', 'City', 'dealerCity', 'Dealer', { width: 'third' }),
    field('dp-dealer-state', 'State', 'dealerState', 'Dealer', { width: 'third' }),
    field('dp-dealer-zip', 'ZIP', 'dealerZip', 'Dealer', { width: 'third' }),
    field('dp-dealer-phone', 'Phone', 'dealerPhone', 'Dealer', { width: 'half' }),
    field('dp-buyer-name', 'Buyer Full Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('dp-buyer-address', 'Address', 'buyerAddress', 'Buyer', { width: 'half' }),
    field('dp-buyer-phone', 'Phone', 'buyerPhone', 'Buyer', { width: 'half' }),
    field('dp-cobuyer', 'Co-Buyer Name', 'coBuyerFullName', 'Buyer', { width: 'half' }),
    field('dp-year', 'Year', 'vehicleYear', 'Vehicle', { width: 'third' }),
    field('dp-make', 'Make', 'vehicleMake', 'Vehicle', { width: 'third' }),
    field('dp-model', 'Model', 'vehicleModel', 'Vehicle', { width: 'third' }),
    field('dp-vin', 'VIN', 'vehicleVIN', 'Vehicle', { width: 'two-thirds' }),
    field('dp-stock', 'Stock #', 'vehicleStockNumber', 'Vehicle', { width: 'third' }),
    field('dp-amount', 'Amount Received', 'downPayment', 'Receipt Details', { type: 'currency', required: true, width: 'half' }),
    field('dp-date', 'Date Received', 'downPaymentDate', 'Receipt Details', { type: 'date', required: true, width: 'half' }),
    field('dp-method', 'Method (Cash / Check / Card)', 'downPaymentMethod', 'Receipt Details', { width: 'half' }),
    field('dp-receipt-no', 'Receipt #', 'downPaymentReceipt', 'Receipt Details', { width: 'half' }),
    field('dp-salesperson', 'Received By', 'salesperson', 'Receipt Details', { required: true, width: 'half' }),
    field('dp-deal-date', 'Deal Date', 'dealDate', 'Receipt Details', { type: 'date', width: 'half' }),
  ],
}

const lienholderPayoffTitle: DealFormTemplate = {
  id: 'lienholder-payoff-title',
  name: 'Lienholder Payoff / Title Request Form',
  shortName: 'Payoff / Title Request',
  category: 'title_registration',
  description: 'Requests payoff information and title release from existing lienholder on a trade or purchased vehicle.',
  version: '1.0',
  printOrder: 31,
  sections: ['Dealer', 'Vehicle', 'Lienholder', 'Payoff Details'],
  fields: [
    field('lp-dealer-name', 'Dealer Name', 'dealerName', 'Dealer', { required: true, width: 'half' }),
    field('lp-dealer-address', 'Address', 'dealerAddress', 'Dealer', { width: 'half' }),
    field('lp-dealer-city', 'City', 'dealerCity', 'Dealer', { width: 'third' }),
    field('lp-dealer-state', 'State', 'dealerState', 'Dealer', { width: 'third' }),
    field('lp-dealer-zip', 'ZIP', 'dealerZip', 'Dealer', { width: 'third' }),
    field('lp-dealer-phone', 'Phone', 'dealerPhone', 'Dealer', { width: 'half' }),
    field('lp-dealer-fax', 'Fax', 'dealerFax', 'Dealer', { width: 'half' }),
    field('lp-year', 'Year', 'vehicleYear', 'Vehicle', { required: true, width: 'third' }),
    field('lp-make', 'Make', 'vehicleMake', 'Vehicle', { required: true, width: 'third' }),
    field('lp-model', 'Model', 'vehicleModel', 'Vehicle', { required: true, width: 'third' }),
    field('lp-vin', 'VIN', 'vehicleVIN', 'Vehicle', { required: true, width: 'two-thirds' }),
    field('lp-mileage', 'Mileage', 'vehicleMileage', 'Vehicle', { type: 'number', width: 'third' }),
    field('lp-buyer', 'Registered Owner / Buyer', 'buyerFullName', 'Vehicle', { required: true, width: 'full' }),
    field('lp-lienholder', 'Lienholder Name', 'lenderName', 'Lienholder', { required: true, width: 'half' }),
    field('lp-lienholder-address', 'Lienholder Address', 'lenderAddress', 'Lienholder', { width: 'half' }),
    field('lp-account', 'Account / Loan #', 'lienholderAccount', 'Lienholder', { width: 'half' }),
    field('lp-rep', 'Lienholder Rep Name', 'lienholderRepName', 'Lienholder', { width: 'half' }),
    field('lp-payoff-amount', 'Payoff Amount', 'lienholderPayoffAmount', 'Payoff Details', { type: 'currency', required: true, width: 'half' }),
    field('lp-good-until', 'Good Until (Date)', 'lienholderGoodUntil', 'Payoff Details', { type: 'date', required: true, width: 'half' }),
    field('lp-per-diem', 'Daily Per Diem', 'lienholderPerDiem', 'Payoff Details', { type: 'currency', width: 'half' }),
    field('lp-deal-date', 'Request Date', 'dealDate', 'Payoff Details', { type: 'date', width: 'half' }),
    field('lp-salesperson', 'Requested By', 'salesperson', 'Payoff Details', { width: 'half' }),
  ],
}

const referencesLandlord: DealFormTemplate = {
  id: 'references-landlord',
  name: 'References and Landlord Information Form',
  shortName: 'References / Landlord',
  category: 'buyer_information',
  description: 'Collects personal and professional references as well as landlord contact information for credit verification.',
  version: '1.0',
  printOrder: 6,
  sections: ['Buyer', 'Reference 1', 'Reference 2', 'Reference 3', 'Landlord / Mortgage'],
  fields: [
    field('rl-buyer-name', 'Buyer Full Name', 'buyerFullName', 'Buyer', { required: true, width: 'half' }),
    field('rl-buyer-phone', 'Phone', 'buyerPhone', 'Buyer', { width: 'half' }),
    field('rl-buyer-address', 'Current Address', 'buyerAddress', 'Buyer', { width: 'full' }),
    field('rl-buyer-city', 'City', 'buyerCity', 'Buyer', { width: 'third' }),
    field('rl-buyer-state', 'State', 'buyerState', 'Buyer', { width: 'third' }),
    field('rl-buyer-zip', 'ZIP', 'buyerZip', 'Buyer', { width: 'third' }),
    field('rl-ref1-name', 'Reference 1 Name', 'reference1Name', 'Reference 1', { required: true, width: 'half' }),
    field('rl-ref1-phone', 'Reference 1 Phone', 'reference1Phone', 'Reference 1', { width: 'half' }),
    field('rl-ref1-rel', 'Relationship', 'reference1Relationship', 'Reference 1', { width: 'half' }),
    field('rl-ref1-addr', 'Address', 'reference1Address', 'Reference 1', { width: 'half' }),
    field('rl-ref2-name', 'Reference 2 Name', 'reference2Name', 'Reference 2', { required: true, width: 'half' }),
    field('rl-ref2-phone', 'Reference 2 Phone', 'reference2Phone', 'Reference 2', { width: 'half' }),
    field('rl-ref2-rel', 'Relationship', 'reference2Relationship', 'Reference 2', { width: 'half' }),
    field('rl-ref2-addr', 'Address', 'reference2Address', 'Reference 2', { width: 'half' }),
    field('rl-ref3-name', 'Reference 3 Name', 'reference3Name', 'Reference 3', { width: 'half' }),
    field('rl-ref3-phone', 'Reference 3 Phone', 'reference3Phone', 'Reference 3', { width: 'half' }),
    field('rl-ref3-rel', 'Relationship', 'reference3Relationship', 'Reference 3', { width: 'half' }),
    field('rl-ref3-addr', 'Address', 'reference3Address', 'Reference 3', { width: 'half' }),
    field('rl-landlord-name', 'Landlord / Mortgage Company', 'landlordName', 'Landlord / Mortgage', { width: 'half' }),
    field('rl-landlord-phone', 'Landlord Phone', 'landlordPhone', 'Landlord / Mortgage', { width: 'half' }),
    field('rl-housing', 'Housing Status (Own / Rent)', 'buyerHousingStatus', 'Landlord / Mortgage', { width: 'half' }),
    field('rl-housing-pmt', 'Monthly Housing Payment', 'buyerMonthlyHousing', 'Landlord / Mortgage', { type: 'currency', width: 'half' }),
    field('rl-date', 'Date', 'dealDate', 'Landlord / Mortgage', { type: 'date', width: 'half' }),
  ],
}

// ---------------------------------------------------------------------------
// Template registry
// ---------------------------------------------------------------------------

export const DEAL_FORM_TEMPLATES: DealFormTemplate[] = [
  buyersOrder,
  retailPurchaseAgreement,
  dealRecap,
  buyerInformationSheet,
  coBuyerInformationSheet,
  creditApplicationPrintout,
  fundingLenderCoverSheet,
  tradeAppraisalWorksheet,
  privacyNotice,
  odometerStatement,
  arbitrationAcknowledgment,
  weOwe,
  insuranceVerification,
  titleRegistrationWorksheet,
  // NCM-style forms
  vehicleEquipmentCondition,
  checkRequest,
  paymentAgreement,
  fourSquareWorksheet,
  downPaymentReceipt,
  lienholderPayoffTitle,
  referencesLandlord,
]

export function getTemplate(id: string): DealFormTemplate | undefined {
  return DEAL_FORM_TEMPLATES.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: DealFormTemplate['category']): DealFormTemplate[] {
  return DEAL_FORM_TEMPLATES.filter((t) => t.category === category).sort(
    (a, b) => a.printOrder - b.printOrder
  )
}

// ---------------------------------------------------------------------------
// Packet presets
// ---------------------------------------------------------------------------

export const PACKET_PRESETS: PacketPreset[] = [
  {
    id: 'standard-retail',
    name: 'Standard Retail Packet',
    description: "Buyer's Order, Retail Agreement, Deal Recap, Buyer Info, Privacy Notice, Odometer",
    formIds: [
      'buyers-order',
      'retail-purchase-agreement',
      'deal-recap',
      'buyer-information-sheet',
      'privacy-notice',
      'odometer-statement',
    ],
    dealTypes: ['retail_finance', 'cash'],
  },
  {
    id: 'finance-packet',
    name: 'Finance Deal Packet',
    description: 'Full finance packet including credit app, lender cover sheet, and all deal docs',
    formIds: [
      'buyers-order',
      'retail-purchase-agreement',
      'deal-recap',
      'buyer-information-sheet',
      'credit-application-printout',
      'funding-lender-cover-sheet',
      'privacy-notice',
      'odometer-statement',
    ],
    dealTypes: ['retail_finance'],
  },
  {
    id: 'cash-deal',
    name: 'Cash Deal Packet',
    description: "Buyer's Order, Retail Agreement, Privacy Notice, Odometer",
    formIds: [
      'buyers-order',
      'retail-purchase-agreement',
      'buyer-information-sheet',
      'privacy-notice',
      'odometer-statement',
    ],
    dealTypes: ['cash'],
  },
  {
    id: 'delivery-packet',
    name: 'Delivery Packet',
    description: 'Delivery acknowledgment, We Owe, Insurance Verification, Odometer',
    formIds: [
      'arbitration-acknowledgment',
      'we-owe',
      'insurance-verification',
      'odometer-statement',
    ],
  },
  {
    id: 'title-packet',
    name: 'Title Packet',
    description: 'Title worksheet and odometer for title processing',
    formIds: ['title-registration-worksheet', 'odometer-statement'],
  },
  {
    id: 'trade-packet',
    name: 'Trade Packet',
    description: 'Trade worksheet and related documents',
    formIds: ['trade-appraisal-worksheet', 'buyers-order'],
  },
  // NCM-style packs
  {
    id: 'retail-basic-pack',
    name: 'Retail Basic Pack',
    description: 'Four Square Worksheet, Down Payment Receipt, Payment Agreement',
    formIds: [
      'four-square-worksheet',
      'down-payment-receipt',
      'payment-agreement',
    ],
    dealTypes: ['retail_finance', 'cash'],
  },
  {
    id: 'retail-finance-pack',
    name: 'Retail Finance Pack',
    description: 'Four Square Worksheet, Down Payment Receipt, References / Landlord, Payment Agreement',
    formIds: [
      'four-square-worksheet',
      'down-payment-receipt',
      'references-landlord',
      'payment-agreement',
    ],
    dealTypes: ['retail_finance'],
  },
  {
    id: 'trade-payoff-pack',
    name: 'Trade / Payoff Pack',
    description: 'Lienholder Payoff / Title Request Form, Vehicle Equipment / Condition Form',
    formIds: [
      'lienholder-payoff-title',
      'vehicle-equipment-condition',
    ],
  },
  {
    id: 'internal-ops-pack',
    name: 'Internal Ops Pack',
    description: 'Check Request Form for internal dealership disbursements',
    formIds: [
      'check-request',
    ],
  },
]

export const FORM_CATEGORY_LABELS: Record<DealFormTemplate['category'], string> = {
  buyer_information: 'Buyer Information',
  deal_documents: 'Deal Documents',
  disclosure: 'Disclosures',
  trade: 'Trade',
  credit_finance: 'Credit & Finance',
  title_registration: 'Title & Registration',
  delivery: 'Delivery',
  wholesale: 'Wholesale',
}
