export type AssistantMode =
  | 'debug_problem'
  | 'trace_workflow'
  | 'review_code'
  | 'implement_change'
  | 'improve_ui'
  | 'diagnose_deploy'
  | 'diagnose_data_flow'
  | 'explain_feature'
  | 'find_root_cause'
  | 'apply_safe_fix'
  | 'implementation_plan'

export type AssistantLayer =
  | 'ui'
  | 'state_data_flow'
  | 'form_action_logic'
  | 'lead_workflow_logic'
  | 'task_appointment_logic'
  | 'crm_status_logic'
  | 'api_service_layer'
  | 'auth_session'
  | 'db_schema_query'
  | 'deployment_build'
  | 'env_config'
  | 'integration'

export type AssistantActionId =
  | 'debug-issue'
  | 'trace-workflow'
  | 'review-page'
  | 'improve-ui'
  | 'find-root-cause'
  | 'explain-feature'
  | 'diagnose-missing-activity'
  | 'fix-save-update'
  | 'diagnose-reminder-task-appointment'
  | 'diagnose-lead-status'
  | 'diagnose-deploy-config'
  | 'apply-safe-fix'
  | 'summarize-changes'
  | 'create-implementation-plan'
  | 'trace-lead-follow-up-chain'
  | 'review-salesperson-workflow'
  | 'review-manager-visibility'

export interface AssistantAction {
  id: AssistantActionId
  label: string
  description: string
  mode: AssistantMode
}

export interface AssistantInputContext {
  leadCount: number
  eventCount: number
  taskCount: number
  pendingApprovalCount: number
  unhealthyIntegrationCount: number
  leadHint?: string
  relatedEventNames?: string[]
  relatedTaskTitles?: string[]
}

/** A concrete, per-file patch recommendation generated by the diagnostics engine. */
export interface CodePatchProposal {
  file: string
  description: string
  rationale: string
  changeType: 'fix' | 'improvement' | 'refactor' | 'config'
  priority: 'critical' | 'high' | 'medium' | 'low'
  /** Human-readable pseudocode or narrative describing what the change should do. */
  pseudocodeSuggestion: string
  regressionRisk: 'high' | 'medium' | 'low'
}

/** Result of a single deploy/env diagnostic check. */
export interface DeployDiagnosticResult {
  item: string
  status: 'ok' | 'warning' | 'error' | 'unknown'
  detail: string
  remediation?: string
}

/** A correlated timeline event from events, tasks, or appointments for a lead. */
export interface LeadTimelineEvent {
  id: string
  timestamp: string
  type: 'lead_event' | 'task' | 'appointment' | 'audit'
  label: string
  detail: string
  severity: 'info' | 'warning' | 'success' | 'error'
}

/** An approval-gated fix proposal surfaced by the assistant. */
export interface AssistantFixProposal {
  id: string
  actionId: AssistantActionId
  issueSummary: string
  patchProposals: CodePatchProposal[]
  status: 'draft' | 'pending_approval' | 'approved' | 'denied'
  approvalId?: string
  createdAt: string
}

export interface AssistantReport {
  objective: string
  diagnosis: string
  rootCause: string
  confidence: number
  impactedLayers: AssistantLayer[]
  impactedFiles: string[]
  fixOrImprovementPath: string[]
  changesMade: string[]
  validationSteps: string[]
  risksAndFollowUps: string[]
  selfReviewChecklist: string[]
  worklogSummary: string
  /** Per-file patch proposals generated by the diagnostics engine. */
  codePatchProposals: CodePatchProposal[]
  /** Deploy/env diagnostics for deploy-related analysis modes. */
  deployDiagnostics: DeployDiagnosticResult[]
}

export interface AssistantWorklogEntry {
  id: string
  timestamp: string
  actionId: AssistantActionId
  issueSummary: string
  symptoms: string
  likelyCause: string
  filesInspected: string[]
  changesProposed: string[]
  validationSteps: string[]
  openQuestions: string[]
}
